apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "turborepo-remote-cache.fullname" . }}
  labels:
    {{- include "turborepo-remote-cache.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "turborepo-remote-cache.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "turborepo-remote-cache.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: turborepo-remote-cache
          hostPath:
            path: /tmp/turborepo
      serviceAccountName: {{ include "turborepo-remote-cache.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
            - mountPath: "/tmp/turborepo"
              name: turborepo-remote-cache
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: STORAGE_PROVIDER
              value: "{{ .Values.config.storageProvider }}"
            - name: LOG_LEVEL
              value: "{{ .Values.config.logLevel }}"
            - name: STORAGE_PATH
              value: "{{ .Values.config.storagePath }}"
            - name: STORAGE_PATH_USE_TMP_FOLDER
              value: "{{ .Values.config.storagePathUseTmpFolder }}"
            - name: BODY_LIMIT
              value: "{{ .Values.config.bodyLimit }}"
            - name: TURBO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "turborepo-remote-cache.fullname" . }}
                  key: token
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
