apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turborepo-remote-cache.fullname" . }}
  labels:
    {{- include "turborepo-remote-cache.labels" . | nindent 4 }}
type: Opaque
data:
  apikey: {{ .Values.config.turboToken | b64enc }}
