---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: turborepo-remote-cache
spec:
  storageClassName: "efs-sc"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "50Gi"