{{- if .Values.pvc.create -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: turborepo-remote-cache
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}
{{- end }}